### ISSUE TITLE
FilePath should be absolute

### ISSUE THREAD

**Issue by bilgeulcay** [gokcearslan/CE216-Team5#9]
FilePath that is used in below functions cannot find the file in other devices. 
addTranslation(), deleteWord(), deleteTranslation()

**Comment by gokcearslan** [comment]
The issue is fixed. Now, the new version of the search method uses all seven languages as base.
FilePath should be absolute
FilePath which is used in the below functions cannot find the file in other devices. 
addTranslation(), deleteWord(), deleteTranslation()
The issue is fixed. A way of providing file path that works has been found and implemented to the code.
